In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
np.random.seed(42)
n=20000
custid = np.arange(1,n+1)
name = [f'Cust_{i}' for i in custid]
age = np.random.randint(18,70,n)
gender = np.random.choice(['Male','Female','Others'],n)
city = np.random.choice(['Blr','Mumbai','Chennai','Hyd'],n)
sign_up = pd.date_range(start='01-01-2024',periods=n,freq='H')
income = np.random.randint(10000,1000000,n)
loyal = np.random.uniform(1,10,n)
email = [f'{i.lower()}@gmail.com' for i in name]
phone = np.random.randint(6000000000,9999999999,n, dtype = 'int64')

C:\Users\PRITHVI\AppData\Local\Temp\ipykernel_22188\106653836.py:8: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  sign_up = pd.date_range(start='01-01-2024',periods=n,freq='H')

In [17]:
customers = pd.DataFrame({'Customer_ID':custid,
                          'Customer_name':name,
                          'Age':age,
                          'Gender':gender,
                          'city':city,
                          'signup_date':sign_up,
                          'income':income,
                          'Loyalty_points':loyal,
                          'Email_ID':email,
                          'Phone':phone})

In [18]:
customers.loc[np.random.choice(n,30),'Email_ID']=np.nan

In [19]:
customers.loc[np.random.choice(n,30,replace=False),'Phone']=np.nan

In [20]:
pd.concat([customers,customers.sample(500)])

,Customer_ID,Customer_name,Age,Gender,city,signup_date,income,Loyalty_points,Email_ID,Phone
0,1,Cust_1,56,Male,Mumbai,2024-01-01 00:00:00,486258,2.171743,cust_1@gmail.com,6.502217e+09
1,2,Cust_2,69,Others,Chennai,2024-01-01 01:00:00,479504,4.825786,cust_2@gmail.com,9.798029e+09
2,3,Cust_3,46,Others,Hyd,2024-01-01 02:00:00,140171,1.237801,cust_3@gmail.com,9.709355e+09
3,4,Cust_4,32,Male,Chennai,2024-01-01 03:00:00,495370,8.949870,cust_4@gmail.com,6.604348e+09
4,5,Cust_5,60,Others,Chennai,2024-01-01 04:00:00,738180,3.157356,cust_5@gmail.com,9.951763e+09
...,...,...,...,...,...,...,...,...,...,...
993,994,Cust_994,40,Others,Chennai,2024-02-11 09:00:00,631499,4.979291,cust_994@gmail.com,9.402321e+09
1871,1872,Cust_1872,49,Others,Blr,2024-03-18 23:00:00,49709,1.942466,cust_1872@gmail.com,8.396777e+09
16265,16266,Cust_16266,65,Male,Chennai,2025-11-08 17:00:00,286292,2.671354,cust_16266@gmail.com,8.781736e+09
15523,15524,Cust_15524,60,Others,Mumbai,2025-10-08 19:00:00,822136,7.248715,cust_15524@gmail.com,9.441427e+09
17917,17918,Cust_17918,32,Female,Mumbai,2026-01-16 13:00:00,816578,2.658125,cust_17918@gmail.com,6.368058e+09

In [21]:
np.random.choice([-5,-3,156,178,190],500)

array([ -3, 178,  -5,  -5, 190, 190, 190, 178, 190, 190,  -3,  -3,  -3,
       190, 190, 156, 190, 190, 190,  -3, 190,  -3,  -3, 178, 190,  -3,
        -3,  -3, 190, 156, 190, 190, 156, 190, 178, 178, 190, 178,  -3,
        -5, 190, 156,  -3, 156, 156,  -5, 178, 156, 190, 190,  -3,  -3,
       156,  -5, 178,  -5,  -5,  -3, 178, 156,  -5, 156,  -3, 156, 190,
       178,  -5,  -3, 156,  -3, 190,  -3, 178, 178, 178, 190, 178, 190,
        -5, 190, 156, 178,  -3, 190,  -5, 156,  -5,  -5, 156, 178,  -3,
       156, 178, 178, 190, 178, 156, 178, 190, 190,  -3, 156, 156,  -3,
       156,  -5, 190,  -5, 178,  -3,  -5, 178, 156, 156, 178, 178, 178,
       178, 178,  -3, 178, 156, 156,  -3, 178, 190, 156, 178, 190, 190,
        -5, 190, 190, 156, 190, 190, 156,  -5,  -5, 178, 178, 190, 190,
       178, 178, 190, 156, 156, 156, 178,  -5, 178, 156,  -3, 156,  -3,
       156, 156,  -3, 156,  -3,  -3, 178,  -5, 178,  -5,  -5, 156,  -3,
        -5,  -5,  -5,  -3, 190,  -5,  -3,  -3, 190, 178,  -5, 190, 190,
       178,  -5, 190, 190, 178, 190, 156,  -5,  -5, 178, 190, 156, 156,
       156, 190,  -3, 178,  -3, 178,  -5,  -5, 190, 178,  -3,  -5, 190,
        -5,  -3, 178, 156,  -5, 178,  -5, 178,  -3, 156,  -5, 190, 190,
        -5, 178, 178,  -5, 178,  -5,  -3, 156, 178, 156,  -3, 190,  -3,
        -3, 178, 190, 156, 190,  -3, 190, 178, 178,  -3,  -5, 190, 156,
        -3,  -5, 190,  -5,  -3, 190,  -5,  -5, 178,  -3, 156,  -3,  -3,
       178, 156, 178,  -3,  -5,  -5,  -3, 190,  -3,  -3, 190, 190, 178,
        -5, 190,  -3, 156, 156, 178, 156,  -5,  -3, 156,  -5, 156,  -3,
       178,  -5, 190, 190, 156, 190,  -5, 190,  -5, 190, 178, 156,  -5,
       178, 156, 178, 190,  -5,  -3, 178,  -3,  -5, 190, 190,  -3, 156,
        -3,  -3,  -3,  -3,  -5,  -5,  -3,  -3, 190, 178,  -5, 156, 156,
       156, 178, 190, 178,  -3, 190, 190,  -3, 156, 156,  -5, 156, 178,
       190,  -5,  -5, 156,  -5,  -5,  -3, 156, 156, 190, 178,  -5,  -5,
       178, 178,  -5, 178,  -3, 178, 156,  -5,  -5, 178, 190,  -3, 156,
       178, 190, 178,  -5, 156, 178,  -5,  -3,  -5, 178, 178,  -3, 178,
       190,  -3, 156,  -5, 156,  -3, 190,  -3, 190, 178,  -3, 156,  -5,
        -3,  -5,  -3,  -3,  -3, 178, 156, 178, 156,  -5, 178,  -5,  -3,
       178, 178,  -3, 190,  -5, 156, 156, 156, 178, 156, 156,  -3,  -5,
       178,  -3,  -3, 178,  -3, 190, 178,  -5, 178,  -3,  -3,  -5,  -5,
       190, 178, 156,  -3, 156,  -3,  -5, 156,  -3, 178, 178, 178,  -3,
       178, 190, 190,  -5, 156,  -3, 178, 178,  -5,  -3,  -3, 178,  -3,
       178, 190, 178,  -5,  -5, 178,  -3, 156, 190, 156, 190, 190,  -3,
       190,  -5,  -5, 190, 178, 156,  -3, 190, 190, 190,  -5,  -5, 156,
        -3, 190,  -5,  -5, 178, 190, 190,  -3, 178, 190,  -5, 156,  -3,
       190, 190,  -5, 156,  -5,  -5])

In [22]:
customers.loc[np.random.choice(n,500),'Age'] = np.random.choice([-5,-3,156,178,190],500)

C:\Users\PRITHVI\AppData\Local\Temp\ipykernel_22188\3126308007.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[156  -5  -5  -5 156  -5 156 190 190  -5 178 190 156 190 190  -5 156 178
 156 190 190  -5 178  -3 178 156  -5  -3  -3 156  -5  -3  -5 156 156  -5
 156 156  -3  -5 156 178 178 156 190 178  -3  -3  -3 156 156 178  -3  -3
 190 156 178 178 156  -3  -5 178 156  -3  -3  -3 190  -3 190 156  -3 156
 178  -3 190 178 156  -5 156 178 178 178  -3 156 156 190 156 190  -5  -3
 156  -5 156 190  -5 156  -5  -5  -3  -3  -5 156  -5 156 190 178 156  -3
 156 178  -5 190 190 178 190 156  -5 156 178  -3 190 178  -5  -3  -5 156
  -3 190  -3 156 190 156 156 190 190 156 156 190 156  -5  -5  -5  -5 156
 156  -3  -3  -3  -3 156  -3 156  -5 156  -3 156 156 190  -3 178 178 156
 190 156  -3  -5 156 178 156  -3  -3 178 178 190 190  -5 178 190 178 156
 190 178 178 156 178 190 190  -5  -5 190  -5  -5 156  -3  -5  -3  -5  -3
 178  -3  -3 178 178  -5  -5  -3 190  -3 190 178  -3  -5 156  -5 156 190
  -5  -3 156 178  -3  -5 178 178 178 178  -3 190 178 190 190  -5  -3 178
 156  -5  -3  -3 190  -5  -3  -5  -3 190 178 178  -3  -3  -5 190  -5  -5
 156 156 178 190 190 178 190 156 156 156  -5  -3 178  -5 190  -3 190 178
  -3 156 156  -3 156 156 156 178  -3  -3  -5 190 190  -5 190 156  -3  -5
 178 156 178 156  -5  -3 178  -3 156  -3  -3  -3  -3  -3 190  -3 178 190
 178 156 178 190 156 156  -3 178  -3  -3  -3  -3 190 178 190 190 156  -3
 178 178 178 178  -3 156 190 156 156  -3 156  -5 178  -5  -3 178 156 156
 178  -3  -5  -3 156  -3  -3 156 178 178  -5  -3 190 178 190  -3  -3 178
 156 156 178  -5 156  -5  -3 190 178 190  -3  -3 156 156  -5  -5  -5  -5
 156  -5  -5 178  -3 156 156 178 178 178  -3 156 178  -5  -5 178 178 156
 156 178 190  -3  -3  -3  -3  -3 178 178 190  -5  -3 190  -3 178 178  -3
  -3 190 178  -3 190  -5 190 190  -3  -5 156  -5 156 190  -5 178 156  -5
  -3 156 156 156  -3 178 178 190 190  -5  -5  -5  -3 178  -3  -3 156 190
 190 178 178 156 156  -3 156 190  -5  -5  -3  -3 190  -3 190 178  -5 190
 156 190  -5  -5 156 190  -5 190  -3 190  -5 156  -3 156 156 178 156 190
  -5  -5 190 156 178 178 190 190  -5 190  -3 156  -3 190]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  customers.loc[np.random.choice(n,500),'Age'] = np.random.choice([-5,-3,156,178,190],500)

In [23]:
customers.to_csv('customers.csv',index=False)

**DATASET 2**

In [24]:
np.random.seed(42)
n = 20000

product_id = np.arange(1, n+1)

brands = ['Nike','Samsung','Apple','Sony','LG','Adidas','Puma']
categories = ['Electronics','Clothing','Grocery','Home','Sports']

product_name = [
    f"{np.random.choice(brands)}_{np.random.choice(categories)}_{i}"
    for i in product_id
]

category = np.random.choice(categories, n)

price = np.random.randint(100, 50000, n)
stock = np.random.randint(0, 500, n)
rating = np.round(np.random.uniform(1, 5, n), 1)

products = pd.DataFrame({
    'Product_ID': product_id,
    'Product_Name': product_name,
    'Category': category,
    'Price': price,
    'Stock': stock,
    'Rating': rating
})

In [25]:
products

       Product_ID          Product_Name  Category  Price  Stock  Rating
0               1           Puma_Home_1      Home  46521    152     1.1
1               2          LG_Grocery_2      Home   4953    236     3.5
2               3           LG_Sports_3    Sports  27519    213     4.5
3               4       Puma_Clothing_4    Sports  40963    140     1.2
4               5       Apple_Grocery_5  Clothing  27562    297     1.9
...           ...                   ...       ...    ...    ...     ...
19995       19996  Samsung_Sports_19996    Sports  38360    437     1.6
19996       19997    Nike_Grocery_19997  Clothing  19168     98     3.7
19997       19998   Nike_Clothing_19998    Sports  15787     89     2.1
19998       19999    Sony_Grocery_19999   Grocery   7115    156     1.3
19999       20000      LG_Grocery_20000   Grocery  47740    424     4.6

[20000 rows x 6 columns]